export const cardList = [
  {
    id: 1,
    topic: "Web design",
    title: "Задача 1",
    date: "05.06.2024",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "Research",
    title: "Задача 2",
    date: "06.06.2024",
    status: "Без статуса",
  },
  {
    id: 3,
    topic: "Copywriting",
    title: "Задача 3",
    date: "07.06.2024",
    status: "Без статуса",
  },
  {
    id: 4,
    topic: "Research",
    title: "Задача 4",
    date: "08.06.2024",
    status: "Без статуса",
  },
  {
    id: 5,
    topic: "Copywriting",
    title: "Задача 5",
    date: "09.06.2024",
    status: "Без статуса",
  },
  {
    id: 6,
    topic: "Research",
    title: "Задача 6",
    date: "11.06.2024",
    status: "Нужно сделать",
  },
  {
    id: 7,
    topic: "Research",
    title: "Задача 7",
    date: "11.06.2024",
    status: "В работе",
  },
  {
    id: 8,
    topic: "Copywriting",
    title: "Задача 8",
    date: "12.06.2024",
    status: "В работе",
  },
  {
    id: 9,
    topic: "Web design",
    title: "Задача 9",
    date: "13.06.2024",
    status: "В работе",
  },
  {
    id: 10,
    topic: "Research",
    title: "Задача 10",
    date: "14.06.2024",
    status: "Тестирование",
  },
  {
    id: 11,
    topic: "Research",
    title: "Задача 11",
    date: "15.06.2024",
    status: "Готово",
  },
];
